name: Build Site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'

    - name: npm ci
      run: |
        npm ci
  
    - name: Check translations
      run: |
        npm run i18n-check

    - name: build
      run: |
        npm run build
    - uses: actions/upload-artifact@v7
      with:
        name: Public
        path: public/
